### ISSUE TITLE
Undefined Variable "smartApi"

### ISSUE THREAD

**Issue by aashishparyaniba** [angelbroking-github/smartapi-python#26]
This error is comming from 63 and 76 lines no., don't know what to do.

**Comment by ananya-007** [comment]
@aashishparyaniba Please provide more details about the like the complete stacktrace, file you are referring to etc.

**Comment by kamalkishor304** [comment]
Even I'm facing the same issue.

Traceback (most recent call last):
  File "D:/kkpra/Documents/Python/SmartAPI/main.py", line 79, in <module>
    smartapi.getCandleData(historicParam)
AttributeError: module 'smartapi' has no attribute 'getCandleData'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/kkpra/Documents/Python/SmartAPI/main.py", line 81, in <module>
    print("Historic Api failed: {}".format(e.message))
AttributeError: 'AttributeError' object has no attribute 'message'
