### ISSUE TITLE
User Is Blocked', 'errorcode': 'AB1007', 'data': None

### ISSUE THREAD

**Issue by davevediky** [angelbroking-github/smartapi-python#52]
refreshToken= data['data']['refreshToken']
TypeError: 'NoneType' object is not subscriptable

when i print(data) i got 
{'status': False, 'message': 'User Is Blocked', 'errorcode': 'AB1007', 'data': None}
Traceback (most recent call last):
  File "C:\Users\Vedik\Desktop\smartapi-python-main\example\sample.py", line 13, in <module>
    refreshToken= data['data']['refreshToken']
TypeError: 'NoneType' object is not subscriptable

**Comment by virajkadam** [comment]
> ```
> refreshToken= data['data']['refreshToken']
> ```
> 
> TypeError: 'NoneType' object is not subscriptable
> 
> when i print(data) i got {'status': False, 'message': 'User Is Blocked', 'errorcode': 'AB1007', 'data': None} Traceback (most recent call last): File "C:\Users\Vedik\Desktop\smartapi-python-main\example\sample.py", line 13, in refreshToken= data['data']['refreshToken'] TypeError: 'NoneType' object is not subscriptable

has it unblocked yet ? What is process to unblock ?
